# --- GRUNDLEGENDE EINSTELLUNGEN ---

# Öffnet den Standard-MQTT-Port. 
listener 1883

# Erlaubt Verbindungen ohne Benutzername und Passwort.
allow_anonymous true


# --- DATENSPEICHERUNG (PERSISTENCE) ---
persistence true
persistence_location /mosquitto/data/

# --- LOGGING ---
log_dest stdout
log_dest file /mosquitto/log/mosquitto.log